name: docker-push

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build application
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: rapour/playful-app
      -
        name: Build particle
        uses: docker/build-push-action@v3
        with:
          context: ./particle
          file: ./particle/Dockerfile
          push: true
          tags: rapour/playful-particles